/**
 * Generates docs/CANVAS_API.md from src/api/schema.ts and copies the schema
 * and bridge protocol into the MCP CLI. Run with `npm run api:gen`
 * (needs Node 22.18+, which runs TypeScript directly).
 */
import { copyFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  API_VERSION,
  EVENT_NAMES,
  TOOLS,
  takesOptionsObject,
  toMcpName,
  type JsonSchema,
  type ToolSpec,
} from "../src/api/schema.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function typeOf(s: JsonSchema): string {
  if (s.enum) return s.enum.map((v) => `'${v}'`).join(" | ");
  if (s.type === "array") return `${s.items ? typeOf(s.items) : "any"}[]`;
  if (s.type === "object" && s.properties) {
    const inner = Object.entries(s.properties)
      .map(
        ([k, v]) => `${k}${s.required?.includes(k) ? "" : "?"}: ${typeOf(v)}`
      )
      .join(", ");
    return `{${inner}}`;
  }
  return s.type ?? (s.description === "function" ? "function" : "any");
}

function signature(t: ToolSpec): string {
  const params = t.params
    .map((p) => `${p.name}${p.required ? "" : "?"}: ${typeOf(p.schema)}`)
    .join(", ");
  return `paperos.${t.name}(${params})`;
}

/** Pipes inside a table cell must be escaped. */
const cell = (s: string) => s.replace(/\|/g, "\\|");

function paramRows(t: ToolSpec): string {
  if (t.params.length === 0) return "";
  const rows = t.params.flatMap((p) => {
    const base = `| \`${p.name}\` | ${p.required ? "yes" : "no"} | \`${cell(typeOf(p.schema))}\` | ${p.description} |`;
    const props =
      p.schema.type === "object" && p.schema.properties
        ? Object.entries(p.schema.properties).map(
            ([k, v]) =>
              `| \`${p.name}.${k}\` | ${p.schema.required?.includes(k) ? "yes" : "no"} | \`${cell(typeOf(v))}\` | ${v.description ?? ""} |`
          )
        : [];
    return [base, ...props];
  });
  return [
    "",
    "| Parameter | Required | Type | Description |",
    "| --- | --- | --- | --- |",
    ...rows,
  ].join("\n");
}

function toolSection(t: ToolSpec): string {
  const flags = [
    t.mutates ? "changes state" : "read-only",
    t.browserOnly
      ? "scripts only (takes a callback)"
      : `MCP tool \`${toMcpName(t.name)}\``,
    takesOptionsObject(t) ? "object-style call passes the object itself" : null,
  ]
    .filter(Boolean)
    .join(" · ");
  return [
    `#### \`${t.name}\``,
    "",
    "```ts",
    signature(t),
    "```",
    "",
    t.description,
    "",
    `Returns \`${t.returns}\`. ${flags}.`,
    paramRows(t),
    "",
  ].join("\n");
}

const namespaces = [...new Set(TOOLS.map((t) => t.name.split(".")[0]))];

const intro = `# Canvas API

<!-- Generated by scripts/gen-api.ts from src/api/schema.ts. Do not edit by hand: run \`npm run api:gen\`. -->

The Canvas API is the programmable surface of the PaperOS desktop: one
object, \`paperos\`, whose namespaces cover windows, layouts, workspaces,
projects, files, data (tables, rows, schema, bindings), the preview, the
console, commands, the camera and events.
Scripts in the **Script** window, plugins and the MCP bridge all use the same
API, and every method returns plain JSON, so results can be logged, stored or
sent to an agent unchanged.

API version: ${API_VERSION}. ${TOOLS.length} methods in ${namespaces.length} namespaces.

## Where to call it

- **Script window** (New window → Script): the editor's code runs as an async
  function with \`paperos\` and a capturing \`console\` in scope, so
  \`await paperos.files.read("index.html")\` works at the top level.
- **Browser devtools**: \`window.paperos\` is the same object once the
  desktop has mounted. Try \`paperos.windows.list()\`.
- **Plugins**: \`activate(api)\` receives the API plus registration helpers
  (see \`src/plugins/types.ts\`).
- **MCP agents**: \`tools/paperos-mcp\` exposes every method that takes no
  callback as an MCP tool named \`<namespace>_<method>\` (see
  [\`docs/MCP.md\`](MCP.md)).

Scripts and plugins run **inside the page with the page's privileges**, like
code pasted into the devtools. Only run code you trust.

## Conventions

- Window ids are tldraw shape ids (\`shape:...\`); the prefix may be omitted.
- Positions and sizes are in page units (canvas pixels at zoom 1). Windows
  are at least 240 × 160.
- File paths are relative to the project root, POSIX style, no leading slash
  (a leading slash is tolerated). File methods act on the **active** project;
  \`projects.open()\` switches it.
- Methods that change state are synchronous unless they touch files or
  projects, which return promises.
- Bad input throws an \`Error\` with a readable message; nothing is silently
  ignored.
- Object-style calls (\`invokeTool\`, MCP) pass one object whose keys are the
  parameter names. A method whose only parameter is an options object takes
  that object directly: \`windows_create {"kind": "note"}\`.

## Events

\`paperos.events.on(name, callback)\` subscribes (\`"*"\` for everything);
\`events.poll(since)\` returns the last 200 events for callers that cannot hold
a callback (the MCP bridge). Each event is \`{seq, name, time, payload}\`.

| Event | Payload |
| --- | --- |
| \`window.created\` | \`{id, kind, title}\` |
| \`window.closed\` | \`{id, kind, title}\` |
| \`window.focused\` | \`{id, kind, title}\` |
| \`layout.changed\` | \`{preset, tiled: string[]}\` |
| \`file.changed\` | \`{project, path, kind: 'write' \\| 'mkdir' \\| 'rename' \\| 'delete', to?}\` |
| \`command.run\` | \`{id}\` |
| \`project.changed\` | \`{id, name}\` |
| \`data.changed\` | \`{project}\` (a table or the schema changed) |

(${EVENT_NAMES.length} events.)

## Examples

\`\`\`js
// Tile everything in a grid and zoom to it
paperos.layout.apply("grid");
paperos.canvas.zoomTo();

// Open every JavaScript file of the project
const files = await paperos.files.list();
for (const f of files.filter((f) => f.path.endsWith(".js"))) {
  paperos.files.open(f.path);
}

// One note per file, then a screenshot
for (const f of files) {
  paperos.windows.create({ kind: "note", title: f.path, content: f.path });
}
const shot = await paperos.canvas.screenshot();
console.log(shot.width, shot.height);

// React to windows being created
const off = paperos.events.on("window.created", (e) => console.log(e.payload));
\`\`\`

## Reference
`;

const body = namespaces
  .map((ns) => {
    const tools = TOOLS.filter((t) => t.name.startsWith(`${ns}.`));
    return [`### \`${ns}\``, "", ...tools.map(toolSection)].join("\n");
  })
  .join("\n");

writeFileSync(join(root, "docs/CANVAS_API.md"), `${intro}\n${body}`);

// The MCP CLI compiles on its own; give it verbatim copies of the shared modules.
const shared = join(root, "tools/paperos-mcp/src/shared");
mkdirSync(shared, { recursive: true });
for (const f of ["schema.ts", "bridge-protocol.ts"]) {
  copyFileSync(join(root, "src/api", f), join(shared, f));
}
console.log("Wrote docs/CANVAS_API.md and tools/paperos-mcp/src/shared/*");
