/**
 * The curated boards the sample project ships: left-to-right flows of
 * sections (frames of windows) that read as a flowchart of panels and
 * grouped panels. Each is a `boards/<name>.json` file (see `src/boards/`).
 */
import type { BoardDef } from "@/boards/model";
import type { FileMap } from "./types";

const json = (v: unknown) => JSON.stringify(v, null, 2) + "\n";

const SCRIPT_BUILD = `// Runs against the Canvas API. Ctrl+Enter to run.
// Count what the product is made of, then zoom to the preview row.
const tables = await paperos.data.tables();
console.log(tables.map((t) => t.name + " (" + t.rowCount + " rows)").join(", "));
const previews = paperos.windows.list().filter((w) => w.kind === "preview");
paperos.canvas.zoomTo(previews.map((w) => w.id));
return { tables: tables.length, previews: previews.length };
`;

const SCRIPT_AGENT = `// What an agent does over the MCP bridge, as a script:
// read the model, then generate windows on the canvas.
const tables = await paperos.data.tables();
const notes = tables.map((t, i) =>
  paperos.windows.create({
    kind: "note",
    title: t.name,
    content: t.columns.map((c) => c.name + ": " + c.type).join("\\n"),
    rect: { x: 4200, y: 200 + i * 260, w: 320, h: 220 },
  })
);
const section = paperos.sections.create("Generated by script", notes.map((n) => n.id));
console.log("created", notes.length, "notes in", section.title);
return section;
`;

const NOTE_AGENT = `An agent connected over the MCP bridge sees every tool call here.

1. Click "Agent bridge" in the top bar and run npm run mcp.
2. Ask Claude to "open the roles table and tile it next to the schema".
3. Watch the calls arrive; pause them from this window.`;

const NOTE_MAP = `The project map is generated, not drawn:

paperos.map.generate()

lays out Data, Code, Design, Components, Pages and UX flows as frames of cards with arrows from the bindings. Regenerate keeps the cards you moved.`;

const card = (
  key: string,
  subtitle: string,
  icon: string,
  section: string,
  facts: string[],
  target: Record<string, unknown>
) => ({ key, subtitle, icon, section, facts, target });

export function buildProductBoard(): BoardDef {
  return {
    name: "build-product",
    title: "Build a product",
    description:
      "Data tables, the schema, tokens and gallery, the Page Builder, a preview at three device sizes, and the console: left to right, one step each.",
    sections: [
      {
        id: "data",
        title: "1. Data: tables as files",
        grid: "grid",
        cell: { w: 520, h: 360 },
        windows: [
          { id: "t-roles", kind: "data", content: { table: "roles" } },
          { id: "t-users", kind: "data", content: { table: "users" } },
          { id: "t-menu", kind: "data", content: { table: "menu_items" } },
          { id: "t-pages", kind: "data", content: { table: "pages" } },
        ],
        notes: "Every table is a JSON file; the Data window edits the rows.",
      },
      {
        id: "schema",
        title: "2. Schema: how the tables relate",
        grid: "single",
        windows: [
          {
            id: "erd",
            kind: "schema",
            title: "Schema",
            size: { w: 760, h: 560 },
          },
        ],
        notes: "References draw as lines; add a column and every row migrates.",
      },
      {
        id: "design",
        title: "3. Design: tokens and the component library",
        grid: "stack",
        windows: [
          {
            id: "tokens",
            kind: "design",
            title: "Design tokens",
            content: { tab: "tokens" },
            size: { w: 900, h: 520 },
          },
          {
            id: "gallery",
            kind: "design",
            title: "Component gallery",
            content: { tab: "components" },
            size: { w: 900, h: 520 },
          },
        ],
        notes: "Paper and ink tokens; 35 components that read the tables.",
      },
      {
        id: "builder",
        title: "4. Page Builder: compose from components",
        grid: "single",
        windows: [
          {
            id: "pb",
            kind: "pages",
            title: "Page: home",
            content: { page: "home", device: "desktop" },
            size: { w: 1120, h: 720 },
          },
        ],
        notes:
          "Blocks on a 12-column grid, bound to tables, previewed per device.",
      },
      {
        id: "preview",
        title: "5. Preview: phone, tablet, desktop",
        grid: "row",
        windows: [
          {
            id: "phone",
            kind: "preview",
            title: "Phone 390",
            content: "pages/home.json",
            size: { w: 390, h: 820 },
          },
          {
            id: "tablet",
            kind: "preview",
            title: "Tablet 820",
            content: "pages/home.json",
            size: { w: 820, h: 820 },
          },
          {
            id: "desktop",
            kind: "preview",
            title: "Desktop 1280",
            content: "pages/home.json",
            size: { w: 1280, h: 820 },
          },
        ],
        notes: "One page, three widths; the same tokens and tables everywhere.",
      },
      {
        id: "console",
        title: "6. Script and console",
        grid: "stack",
        windows: [
          {
            id: "script",
            kind: "script",
            title: "Script",
            content: SCRIPT_BUILD,
            size: { w: 640, h: 420 },
          },
          {
            id: "log",
            kind: "console",
            title: "Console",
            size: { w: 640, h: 300 },
          },
        ],
        notes: "Everything on the canvas is scriptable through paperos.*",
      },
    ],
    arrows: [
      { from: "data", to: "schema", label: "tables" },
      { from: "erd", to: "tokens", label: "columns drive forms and tables" },
      { from: "gallery", to: "pb", label: "components" },
      { from: "pb", to: "phone", label: "renders" },
      { from: "pb", to: "tablet", label: "renders" },
      { from: "pb", to: "desktop", label: "renders" },
      { from: "desktop", to: "log", label: "console.log" },
      { from: "script", to: "preview", label: "zooms to the previews" },
    ],
    steps: [
      {
        section: "data",
        title: "Start with data",
        caption:
          "Four tables as JSON files. Edit a cell here and every page that binds the table re-renders.",
      },
      {
        section: "schema",
        title: "See how it connects",
        caption:
          "The schema window draws references between tables and migrates rows when a column changes.",
      },
      {
        section: "design",
        title: "Make it look like something",
        caption:
          "Tokens set the palette, type and depth; the gallery shows every component rendered from them.",
      },
      {
        section: "builder",
        title: "Compose the page",
        caption:
          "Blocks from the library on a 12-column grid, each bound to a table. The file is pages/home.json.",
      },
      {
        section: "preview",
        title: "Check every device",
        caption:
          "Phone, tablet and desktop previews of the same page, live from the same buffers.",
      },
      {
        section: "console",
        title: "Automate it",
        caption:
          "A script counts the tables and zooms to the previews; the console shows what the page logs.",
      },
    ],
  };
}

export function shipFeatureBoard(): BoardDef {
  return {
    name: "ship-feature",
    title: "Ship a feature",
    description:
      "Files, the three files a feature touches, the preview, the console it logs to, and the table it reads.",
    sections: [
      {
        id: "files",
        title: "1. Files",
        grid: "single",
        windows: [
          {
            id: "tree",
            kind: "files",
            title: "Files",
            size: { w: 320, h: 720 },
          },
        ],
        notes: "The project tree. Click a file to open it in an editor.",
      },
      {
        id: "editors",
        title: "2. Edit the three files involved",
        grid: "rows",
        cell: { w: 820, h: 300 },
        windows: [
          { id: "e-html", kind: "editor", content: { file: "index.html" } },
          { id: "e-css", kind: "editor", content: { file: "styles.css" } },
          { id: "e-js", kind: "editor", content: { file: "app.js" } },
        ],
        notes:
          "Markup, styles and behavior. Ctrl+S saves; Shift+Alt+F formats.",
      },
      {
        id: "preview",
        title: "3. Preview",
        grid: "single",
        windows: [
          {
            id: "prev",
            kind: "preview",
            title: "Preview: index.html",
            content: "index.html",
            size: { w: 900, h: 620 },
          },
        ],
        notes: "Rebuilt from the live buffers 300 ms after the last keystroke.",
      },
      {
        id: "console",
        title: "4. Console",
        grid: "single",
        column: 2,
        windows: [
          {
            id: "log",
            kind: "console",
            title: "Console",
            size: { w: 900, h: 260 },
          },
        ],
        notes:
          "console.* output and errors from the preview; run snippets in it.",
      },
      {
        id: "data",
        title: "5. Data the feature reads",
        grid: "single",
        windows: [
          {
            id: "menu",
            kind: "data",
            content: { table: "menu_items" },
            size: { w: 720, h: 480 },
          },
        ],
        notes:
          "The side menu and the mega menu read menu_items; edit a label here.",
      },
    ],
    arrows: [
      { from: "tree", to: "e-html", label: "open" },
      { from: "tree", to: "e-css", label: "open" },
      { from: "tree", to: "e-js", label: "open" },
      { from: "editors", to: "prev", label: "bundled into srcdoc" },
      { from: "prev", to: "log", label: "console.log" },
      { from: "menu", to: "prev", label: "data-source" },
    ],
    steps: [
      {
        section: "files",
        title: "Find the files",
        caption:
          "The whole project is a tree of text files, in the browser or a folder on disk.",
      },
      {
        section: "editors",
        title: "Change three things",
        caption:
          "The markup, the styles and the script of the feature, each in its own editor.",
      },
      {
        section: "preview",
        title: "See it",
        caption:
          "The preview inlines the files into one document and refreshes as you type.",
      },
      {
        section: "console",
        title: "Read the logs",
        caption:
          "Logs and errors from the preview land here; the input evaluates inside it.",
      },
      {
        section: "data",
        title: "Change the data",
        caption:
          "Menus come from menu_items. Rename an item and both menus update.",
      },
    ],
  };
}

export function agentDrivenBoard(): BoardDef {
  return {
    name: "agent-driven",
    title: "Agent-driven",
    description:
      "A script that drives the canvas, the Agent window where MCP calls arrive, the windows they generate, and the project map they end in.",
    sections: [
      {
        id: "script",
        title: "1. Script: the Canvas API",
        grid: "single",
        windows: [
          {
            id: "code",
            kind: "script",
            title: "Script: generate notes",
            content: SCRIPT_AGENT,
            size: { w: 680, h: 560 },
          },
        ],
        notes: "paperos.* is the same API an agent calls over MCP.",
      },
      {
        id: "agent",
        title: "2. Agent window: calls over the bridge",
        grid: "stack",
        windows: [
          {
            id: "transcript",
            kind: "agent",
            title: "Agent",
            size: { w: 560, h: 380 },
          },
          {
            id: "how",
            kind: "note",
            title: "How to connect",
            content: NOTE_AGENT,
            size: { w: 560, h: 220 },
          },
        ],
        notes: "Every tool call shows here as it arrives; Pause holds them.",
      },
      {
        id: "generated",
        title: "3. Generated windows",
        grid: "grid",
        columns: 2,
        cell: { w: 320, h: 200 },
        windows: [
          {
            id: "g1",
            kind: "card",
            title: "roles",
            content: card(
              "table:roles",
              "table · 3 rows",
              "\u{1F5C3}",
              "data",
              ["id, name, level, description"],
              { type: "table", table: "roles" }
            ),
          },
          {
            id: "g2",
            kind: "card",
            title: "menu_items",
            content: card(
              "table:menu_items",
              "table · 11 rows",
              "\u{1F5C3}",
              "data",
              ["nested by parent_id", "grouped by category"],
              { type: "table", table: "menu_items" }
            ),
          },
          {
            id: "g3",
            kind: "card",
            title: "home",
            content: card(
              "page:home",
              "page · /",
              "\u{1F4D0}",
              "pages",
              ["Topbar, Hero, Section, Grid", "Pricing, FAQ, Footer"],
              { type: "page", name: "home" }
            ),
          },
          {
            id: "g4",
            kind: "card",
            title: "Hero",
            content: card(
              "component:Hero",
              "component · Marketing",
              "\u{1F9E9}",
              "components",
              ["eyebrow, title, subtitle", "variants: center, dark, compact"],
              { type: "component", name: "Hero" }
            ),
          },
        ],
        notes:
          "Cards open the real thing: a table in Data, a page in the Page Builder.",
      },
      {
        id: "map",
        title: "4. Project map",
        grid: "stack",
        windows: [
          {
            id: "readme",
            kind: "markdown",
            title: "README.md",
            content: { file: "README.md" },
            size: { w: 620, h: 420 },
          },
          {
            id: "map-note",
            kind: "note",
            title: "Generate the map",
            content: NOTE_MAP,
            size: { w: 620, h: 200 },
          },
        ],
        notes:
          "paperos.map.generate() lays the whole project out as one flowchart.",
      },
    ],
    arrows: [
      { from: "code", to: "transcript", label: "the same API over MCP" },
      { from: "transcript", to: "generated", label: "creates windows" },
      { from: "g1", to: "g3", label: "bound" },
      { from: "g2", to: "g3", label: "bound" },
      { from: "g4", to: "g3", label: "used by" },
      { from: "generated", to: "map", label: "generates the map" },
    ],
    steps: [
      {
        section: "script",
        title: "Write it once",
        caption:
          "A script runs against paperos.*; Ctrl+Enter creates a note per table and frames them.",
      },
      {
        section: "agent",
        title: "Let an agent do it",
        caption:
          "Over the MCP bridge, Claude calls the same methods; the transcript shows each one.",
      },
      {
        section: "generated",
        title: "What comes out",
        caption:
          "Windows and cards appear on the canvas; each card opens the real table, page or component.",
      },
      {
        section: "map",
        title: "Step back",
        caption:
          "The project map draws everything as sections and arrows; regenerate keeps what you moved.",
      },
    ],
  };
}

export function sampleBoardFiles(): FileMap {
  return {
    "boards/build-product.json": json(buildProductBoard()),
    "boards/ship-feature.json": json(shipFeatureBoard()),
    "boards/agent-driven.json": json(agentDrivenBoard()),
  };
}
